tasks:
  - source: src/scripts/01-get.py
    product:
      nb: src/products/01-extract-pipeline.ipynb
      csv_file: src/data/house_prices.csv
      database: src/data/house_prices.duckdb
  - source: src/scripts/02-cleanup.py
    product:
      nb: src/products/02-cleanup.ipynb
      clean_csv: src/data/house_prices_clean.csv
  - source: src/scripts/03-eda.py
    product:
      nb: src/products/03-eda.ipynb
  - source: src/scripts/04-transform.py
    product:
      nb: src/products/04-transform.ipynb
      transformed_csv: src/data/house_prices_transformed.csv
  - source: src/scripts/05-split.py
    product:
      nb: src/products/05-split.ipynb
      train_data: src/data/house_prices_train.csv
      test_data: src/data/house_prices_test.csv
  - source: src/scripts/06-linear_regressions.py
    product:
      nb: src/products/06-linear_regression.ipynb
      model_file: src/data/linear_regression.pickle
