tasks:
  - source: src/scripts/s01_get.py
    product:
      nb: src/products/01-extract-pipeline.ipynb
      csv_file: src/data/{{dataset_name}}_raw.csv
      database: src/data/{{dataset_name}}.duckdb
    params:
      table_name: '{{dataset_name}}'
      kaggle_owner: '{{kaggle_owner}}'
      kaggle_dataset_name: '{{kaggle_dataset_name}}'
      kaggle_csv: '{{kaggle_csv}}'
  - source: src/scripts/s02_cleanup.py
    product:
      nb: src/products/02-cleanup.ipynb
    params:
      table_name: '{{dataset_name}}'
  - source: src/scripts/s03_eda.py
    product:
      nb: src/products/03-eda.ipynb
    params:
      table_name: '{{dataset_name}}'
  - source: src/scripts/s04_transform.py
    product:
      nb: src/products/04-transform.ipynb
      # transformed_csv: data/house_prices_transformed.csv
    params:
      table_name: '{{dataset_name}}'
      transformed_table_name: '{{dataset_name}}_transformed'
  # - source: scripts/s05_split.py
  #   product:
  #     nb: products/05-split.ipynb
  #     train_data: data/house_prices_train.csv
  #     test_data: data/house_prices_test.csv
  - source: src/scripts/s05_regressions.py
    product:
      nb: src/products/05-linear_regression.ipynb
      model_file: src/data/regression_model.pickle
    params:
      transformed_table_name: '{{dataset_name}}_transformed'
