tasks:
  - source: kaggle/01-get.py
    product:
      nb: kaggle/products/extract-pipeline.ipynb
      csv_file: kaggle/data/house_prices.csv

  - source: kaggle/02-cleanup.py
    product:
      nb: kaggle/products/cleanup.ipynb
      clean_csv: kaggle/data/house_prices_clean.csv
  - source: kaggle/03-eda.py
    product:
      nb: kaggle/products/eda.ipynb
  - source: kaggle/04-transform.py
    product:
      nb: kaggle/products/transform.ipynb
      transformed_csv: kaggle/data/house_prices_transformed.csv
  - source: kaggle/05-split.py
    product:
      nb: kaggle/products/05_split.ipynb
      train_data: kaggle/data/house_prices_train.csv
      test_data: kaggle/data/house_prices_test.csv
  - source: kaggle/06-linear_regressions.py
    product:
      nb: kaggle/products/05_linear_regression.ipynb
      model_file: kaggle/data/linear_regression.pickle
