tasks:
  - source: scripts/01-get.py
    product:
      nb: products/01-extract-pipeline.ipynb
      csv_file: data/house_prices.csv
      database: data/house_prices.duckdb
    params:
      table_name: '{{table_name}}'
  - source: scripts/02-cleanup.py
    product:
      nb: products/02-cleanup.ipynb
      clean_csv: data/house_prices_clean.csv
  - source: scripts/03-eda.py
    product:
      nb: products/03-eda.ipynb
  - source: scripts/04-transform.py
    product:
      nb: products/04-transform.ipynb
      transformed_csv: data/house_prices_transformed.csv
  - source: scripts/05-split.py
    product:
      nb: products/05-split.ipynb
      train_data: data/house_prices_train.csv
      test_data: data/house_prices_test.csv
  - source: scripts/06-linear_regressions.py
    product:
      nb: products/06-linear_regression.ipynb
      model_file: data/linear_regression.pickle
